# Generated by Django 3.1.1 on 2020-09-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200912_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ImageField(default='', upload_to='media/images/blog'),
        ),
    ]
