# Generated by Django 3.1.1 on 2020-09-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200913_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_details',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_image',
            field=models.ImageField(default='', upload_to='images/blog'),
        ),
    ]
