# Generated by Django 3.1.1 on 2020-09-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='events',
        ),
    ]
