# Generated by Django 3.1.1 on 2020-09-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_thought'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
