# Generated by Django 3.1.1 on 2020-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_thought_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thought',
            name='date',
        ),
        migrations.AddField(
            model_name='thought',
            name='day',
            field=models.CharField(choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='monday', max_length=128),
            preserve_default=False,
        ),
    ]
