# Generated by Django 3.1.1 on 2020-09-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_register_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
