# Generated by Django 3.1.1 on 2020-09-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200918_1722'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
